version: "3.7"
services:
  app:
    build:
      args:
        user: war
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php:8.2-fpm
    container_name: php-container
    restart: on-failure
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - network-name
    command: bash -c "composer install && npm install && npm run build && sleep 30 && php artisan migrate && php-fpm"
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - '3306:3306'
    volumes:
      - ./docker-compose/mysql/my.cnf:/etc/my.cnf
      - ./docker-compose/mysql/init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - network-name
  nginx:
    image: nginx:alpine
    container_name: nginx-container
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - network-name
networks:
  network-name:
    driver: bridge
